### PR TITLE
Makes visualization location_slug optional, add provider_id column

### PR DESCRIPTION
**Pull request by brettpalmberg**

### CODE REVIEW

**Comment by brettpalmberg** [comment]
Would like to make the foreign key from `visualization.location_id --> location.id` optional for visualizations. I believe this PR supports this behavior, but a sql migration to modify the table `visualization` is still needed. I did take a cursory look at any other SQL queries to see if this would have impacts on joins, etc, but didn't see anything that looked particularly problematic.

**Comment by adamscarberry** [comment]
Dam Profile Chart currently requires location:

{{base_url}}/locations/lrh-test-project/profile-chart

**Review by adamscarberry — APPROVED** [review]

**Comment by adamscarberry** [comment]
@brettpalmberg  Merge when ready

**Comment by brettpalmberg** [comment]
> @brettpalmberg Merge when ready

Thanks @adamscarberry.

**Comment by adamscarberry** [comment]
@brettpalmberg Any reason not to merge?

**Pull request merged**
